name: lodt_hack
description: Leaders of digital transformation hack solution

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  modal_bottom_sheet: ^2.1.2
  sheet: ^0.0.4+1
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_chat_ui: ^1.6.8
  agora_rtc_engine: ^6.1.1+1
  speech_to_text: ^6.1.1
  excel: 2.1.0
  permission_handler: ^10.2.0
  grpc: ^3.1.0
  calendar_date_picker2: ^0.5.2
  google_fonts: ^4.0.0
  flutter_secure_storage: ^8.0.0
  flutter_multi_formatter: ^2.11.1
  json_serializable: ^6.7.0
  url_launcher: ^6.1.11
  dropdown_button2: ^2.1.3
  flutter_local_notifications: ^14.1.1
  flutter_markdown: ^0.6.15
  table_calendar: ^3.0.9
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  video_player: ^2.6.1

  # to generate protobuf poggers run
  # dart pub global activate protoc_plugin
  # export PATH="$PATH:$HOME/.pub-cache/bin"
  # protoc --dart_out=grpc:lib/generated -Iprotos protos/app.proto google/protobuf/timestamp.proto google/protobuf/empty.proto
  # from the root of project
  protoc_plugin: ^20.0.1

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  sheet: ^0.0.4+1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
