FROM golang:1.20.4-alpine3.18 AS builder

WORKDIR /build

COPY ./go.mod ./go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/api ./cmd/api

FROM gcr.io/distroless/static
USER nonroot:nonroot
COPY --from=builder --chown=nonroot:nonroot /app/api /app/api

ENTRYPOINT [ "/app/api" ]
