// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/app/v1/app.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppServiceClient interface {
	// CreateBusinessUser is a public endpoint for creating a new business user account.
	// An initialized session token is returned on success.
	CreateBusinessUser(ctx context.Context, in *CreateBusinessUserRequest, opts ...grpc.CallOption) (*SessionToken, error)
	// UpdateBusinessUser is an authenticated endpoint which updates the currently authenticated business user's information.
	UpdateBusinessUser(ctx context.Context, in *UpdateBusinessUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteBusinessUser is an authenticated endpoint which deletes the currently authenticated business user's account.
	// Information about the user is stored for retrieval in already passed consultations, however,
	// the user will not be able to login anymore.
	DeleteBusinessUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CreateSession is a public endpoint for creating a new session for an existing user account,
	// both for businesses and authorities. An initialized session token is returned on success.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionToken, error)
	// GetSessionUser is an authenticated endpoint which returns the information about the currently authenticated user.
	GetSessionUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSessionUserResponse, error)
}

type appServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppServiceClient(cc grpc.ClientConnInterface) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) CreateBusinessUser(ctx context.Context, in *CreateBusinessUserRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/ldt_hack.app.v1.AppService/CreateBusinessUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UpdateBusinessUser(ctx context.Context, in *UpdateBusinessUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ldt_hack.app.v1.AppService/UpdateBusinessUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteBusinessUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ldt_hack.app.v1.AppService/DeleteBusinessUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/ldt_hack.app.v1.AppService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetSessionUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSessionUserResponse, error) {
	out := new(GetSessionUserResponse)
	err := c.cc.Invoke(ctx, "/ldt_hack.app.v1.AppService/GetSessionUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
// All implementations must embed UnimplementedAppServiceServer
// for forward compatibility
type AppServiceServer interface {
	// CreateBusinessUser is a public endpoint for creating a new business user account.
	// An initialized session token is returned on success.
	CreateBusinessUser(context.Context, *CreateBusinessUserRequest) (*SessionToken, error)
	// UpdateBusinessUser is an authenticated endpoint which updates the currently authenticated business user's information.
	UpdateBusinessUser(context.Context, *UpdateBusinessUserRequest) (*emptypb.Empty, error)
	// DeleteBusinessUser is an authenticated endpoint which deletes the currently authenticated business user's account.
	// Information about the user is stored for retrieval in already passed consultations, however,
	// the user will not be able to login anymore.
	DeleteBusinessUser(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// CreateSession is a public endpoint for creating a new session for an existing user account,
	// both for businesses and authorities. An initialized session token is returned on success.
	CreateSession(context.Context, *CreateSessionRequest) (*SessionToken, error)
	// GetSessionUser is an authenticated endpoint which returns the information about the currently authenticated user.
	GetSessionUser(context.Context, *emptypb.Empty) (*GetSessionUserResponse, error)
	mustEmbedUnimplementedAppServiceServer()
}

// UnimplementedAppServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAppServiceServer struct {
}

func (UnimplementedAppServiceServer) CreateBusinessUser(context.Context, *CreateBusinessUserRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessUser not implemented")
}
func (UnimplementedAppServiceServer) UpdateBusinessUser(context.Context, *UpdateBusinessUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBusinessUser not implemented")
}
func (UnimplementedAppServiceServer) DeleteBusinessUser(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBusinessUser not implemented")
}
func (UnimplementedAppServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAppServiceServer) GetSessionUser(context.Context, *emptypb.Empty) (*GetSessionUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionUser not implemented")
}
func (UnimplementedAppServiceServer) mustEmbedUnimplementedAppServiceServer() {}

// UnsafeAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServiceServer will
// result in compilation errors.
type UnsafeAppServiceServer interface {
	mustEmbedUnimplementedAppServiceServer()
}

func RegisterAppServiceServer(s grpc.ServiceRegistrar, srv AppServiceServer) {
	s.RegisterService(&AppService_ServiceDesc, srv)
}

func _AppService_CreateBusinessUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateBusinessUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldt_hack.app.v1.AppService/CreateBusinessUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateBusinessUser(ctx, req.(*CreateBusinessUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UpdateBusinessUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UpdateBusinessUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldt_hack.app.v1.AppService/UpdateBusinessUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UpdateBusinessUser(ctx, req.(*UpdateBusinessUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteBusinessUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteBusinessUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldt_hack.app.v1.AppService/DeleteBusinessUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteBusinessUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldt_hack.app.v1.AppService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetSessionUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetSessionUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ldt_hack.app.v1.AppService/GetSessionUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetSessionUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AppService_ServiceDesc is the grpc.ServiceDesc for AppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ldt_hack.app.v1.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBusinessUser",
			Handler:    _AppService_CreateBusinessUser_Handler,
		},
		{
			MethodName: "UpdateBusinessUser",
			Handler:    _AppService_UpdateBusinessUser_Handler,
		},
		{
			MethodName: "DeleteBusinessUser",
			Handler:    _AppService_DeleteBusinessUser_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AppService_CreateSession_Handler,
		},
		{
			MethodName: "GetSessionUser",
			Handler:    _AppService_GetSessionUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/app/v1/app.proto",
}
