replicaCount: 3

image:
  repository: ldt-api
  pullPolicy: IfNotPresent

rasa:
  url: "http://host:5005"

secrets:
  postgres_dsn: "postgres-dsn"
  admin_credentials: "admin-credentials"

service:
  type: NodePort
  ports:
    - name: http
      port: 9080
      node: 30080
    - name: grpc
      port: 9081
      node: 30081

imagePullSecrets: false
